apps/orders/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

app_name = 'orders'

urlpatterns = [
    path('', views.list_orders, name='list_orders'),
    path('list/', views.list_orders, name='list_orders'),
    path('adicionar/', views.add_order, name='add_order'),
    path('editar/<int:id_order>/', views.edit_order, name='edit_order'),
    path('excluir/<int:id_order>/', views.delete_order, name='delete_order'),
]

projetolojaapp/urls.py
from django.contrib import admin
admin.autodiscover()
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('produtos/', include('products.urls', namespace='products')),
    path('redessociais/', include('socialnetworks.urls', namespace='socialnetworks')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('clientes_redessociais/', include('clients.urls', namespace='clients_socialnetworks')),
    path('pedidos/', include('orders.urls', namespace='orders')),
    path('pedidos_itens/', include('orders.itens_urls', namespace='orders_itens')),
]

apps/orders/models.py
from django.db import models
from products.models import Product
from clients.models import Client

# Create your models here.

class Order(models.Model):
    client = models.ForeignKey(Client, null=True, blank=True, on_delete=models.CASCADE)
    STATUS_CHOICES = (
        ('Em andamento', 'Em andamento'),
        ('Finalizado', 'Finalizado'),
        ('Cancelado', 'Cancelado'),
    )
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='Em andamento')
    
    @property
    def total_price(self):
        itens = self.orderitem_set.all()

        if itens.exists():
            valor_final = sum(item.valor_dos_produtos() for item in itens)
            return valor_final
        else:
            return 0,0
            
    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        ordering =['id']
        managed = True
        db_table = 'orders'

class OrderItem(models.Model):
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, null=True, blank=True, on_delete=models.CASCADE)
    quantity = models.IntegerField('Quantidade',null=True, blank=True,default=0)
    unitary_price = models.FloatField('Preço unitario',null=True, blank=True,default=0)

    def valor_dos_produtos(self):
        valor = (self.quantity)*(self.unitary_price)
        return valor

    class Meta:
        verbose_name = 'Item de pedido'
        verbose_name_plural = 'Itens de pedido'
        ordering =['id']

orders/models.py
from django.db import models
from products.models import Product
from clients.models import Client

# Create your models here.

class Order(models.Model):
    total_price = models.FloatField('Preco Total', null=True, blank=True, default=0.0)
    STATUS_CHOICES = (
        ('Em andamento', 'Em andamento'),
        ('Finalizado', 'Finalizado'),
        ('Cancelado', 'Cancelado'),
    )
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='Em andamento')
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    order_item = models.ManyToManyField(Product, through='OrderItem', blank=True)
    
    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        ordering =['id']

    def __str__(self):
        return "%s" % (self.total_price) 


class OrderItem(models.Model):
    quantity = models.IntegerField('Quantidade',null=True, blank=True,default=0)
    unitary_price = models.FloatField('Preco unitario',null=True, blank=True, default=0.0)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Item de pedido'
        verbose_name_plural = 'Itens de pedido'
        ordering =['id']

    def __str__(self):
        return "%s" % (self.quantity) 

apps/orders/forms.py
from django import forms
from .models import Order, OrderItem
from products.models import Product
from clients.models import Client

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ()

class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        exclude = ()

apps/orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from rest_framework import viewsets
from .serializer import OrderSerializer, OrderItemSerializer
from .models import Order, OrderItem
from .forms import OrderForm, OrderItemForm

# Create your views here.

class OrderViewSet(viewsets.ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer  

class OrderItemViewSet(viewsets.ModelViewSet):
    queryset = OrderItem.objects.all()
    serializer_class = OrderItemSerializer

def add_order(request):
    template_name = 'orders/add_order.html'
    context = {}
    if request.method == 'POST':
        form = OrderForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('orders:list_orders')
    form = OrderForm()
    context['form'] = form
    return render(request, template_name, context)


def list_orders(request):
    template_name = 'orders/list_orders.html'
    orders = Order.objects.filter()
    context = {
        'orders': orders
    }
    return render(request, template_name, context)

def edit_order(request, id_order):
    template_name = 'orders/add_order.html'
    context = {}
    order = get_object_or_404(Order, id =id_order)
    if request.method =='POST':
        form = OrderForm(request.POST, instance = order)
        if form.is_valid():
            form.save()
            return redirect('orders:list_orders')
    form = OrderForm(instance=order)
    context['form'] = form
    return render(request, template_name, context)

def delete_order(request, id_order):
    order = Order.objects.get(id=id_order)
    order.delete()
    return redirect('orders:list_orders')

#=======================================================================================================================================================================

def add_orderItem(request):
    template_name = 'orders/add_orderItem.html'
    context = {}
    if request.method == 'POST':
        form = OrderItemForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('/pedidos_itens/')
    form = OrderItemForm()
    context['form'] = form
    return render(request, template_name, context)


def list_orderItens(request):
    template_name = 'orders/list_orderItens.html'
    orderItems = OrderItem.objects.all()  
    context = {
        'orderItems': orderItems  
    }
    return render(request, template_name, context)

def edit_orderItem(request, id_orderItem):
    template_name = 'orders/add_orderItem.html'
    context = {}
    orderItem = get_object_or_404(OrderItem, id=id_orderItem) 
    if request.method == 'POST':
        form = OrderItemForm(request.POST, instance=orderItem) 
        if form.is_valid():
            form.save()
            return redirect('/pedidos_itens/')
    form = OrderItemForm(instance=orderItem)
    context['form'] = form
    return render(request, template_name, context)

def delete_orderItem(request, id_orderItem):
    orderItem = OrderItem.objects.get(id=id_orderItem)
    orderItem.delete()
    return redirect('/pedidos_itens/')

templates/orders/add_order.html
{% extends 'base.html' %}
{% load widget_tweaks %} 

{% block title %}

    Realizar Pedido - {{ block.super }}

{% endblock title %}

{% block body %}

{{ block.super }}

    <div class="container">
        <br />
    <h5><b>Realizar Pedido</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.client.id_for_label }}">Cliente</label>
                    {{ form.client|add_class:"form-control" }}
                 </div>
                 <div class="form-group">
                    <label for="id_status">Status</label>
                    <select name="status" id="id_status" class="form-control">
                        <option value="" disabled selected>Select status</option>
                        <option value="Em andamento"selected>Em andamento</option>
                        <option value="Finalizado">Finalizado</option>
                        <option value="Cancelado">Cancelado</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/orders/add_orderItem.html
{% extends 'base.html' %}
{% load widget_tweaks %} 

{% block title %}

    Realizar Pedido um Produto - {{ block.super }}

{% endblock title %}

{% block body %}

{{ block.super }}

    <div class="container">
        <br />
    <h5><b>Realizar Pedido um Produto</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.product.id_for_label }}">Produto</label>
                    {{ form.product|add_class:"form-control" }} 
                 </div>
                <div class="form-group">
                    <label for="{{ form.order.id_for_label }}">Pedido</label>
                    {{ form.order|add_class:"form-control" }}
                 </div>
                <div class="form-group">
                    <label for="{{ form.quantity.id_for_label }}">Quantidade</label>
                    {{ form.quantity|add_class:"form-control" }}
                 </div>
                <div class="form-group">
                    <label for="{{ form.unitary_price.id_for_label }}">Preço da unidade</label>
                    {{ form.unitary_price|add_class:"form-control" }}
                 </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/orders/list_orderItens.html
{% extends 'base.html' %}

{% block title %}

    Lista de Pedidos de Item - {{ block.super }}

{% endblock title %}

{% block body %}

{{ block.super }}

    <div class="container">
        <br />
        <h5><b>Lista de Pedidos de Item</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'orders:add_orderItem' %}" class="btn btn-primary">Realizar um novo Pedido Item</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome do Produto</th>
                    <th scope="col">Pedido</th>
                    <th scope="col">Preço de unidade</th>
                    <th scope="col">Quantidae</th>
                    <th scope="col">Valor de todas unidades</th>
                    </tr>
                </thead>
                <tbody>
                    {% for orderItem in orderItems %}
                        <tr>
                            <th scope="row">{{ orderItem.id }}</th>
                            {% if orderItem.product %}  
                            <td>{{ orderItem.product.name }}</td>
                            {% else %}
                            <td>Não associado a um produto</td>
                            {% endif %}
                            <td>{{ orderItem.order.id }}</td>
                            <td>{{ orderItem.unitary_price }}</td>
                            <td>{{ orderItem.quantity }}</td>
                            <td>{{ orderItem.valor_dos_produtos }}</td>
                            <td>
                                <a href="{% url 'orders:edit_orderItem' orderItem.id %}" class="btn btn-primary btn-sm">Editar Pedido de Item</a>
                            </td>
                            <td>
                                <a href="{% url 'orders:delete_orderItem' orderItem.id %}" class="btn btn-danger btn-sm ">Excluir Pedido de Item</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}

templates/orders/list_orders.html
{% extends 'base.html' %}

{% block title %}

    Lista de Pedidos - {{ block.super }}

{% endblock title %}s

{% block body %}

{{ block.super }}

    <div class="container">
        <br />
        <h5><b>Lista de Pedidos</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'orders:add_order' %}" class="btn btn-primary">Realizar um novo Pedido</a>
                <br />
                <br />
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Cliente</th>
                            <th scope="col">Status</th>
                            <th scope="col">Preço Total</th>
                            <th scope="col">Pedidos De itens</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                            <tr>
                                <th scope="row">{{ order.id }}</th>
                                {% if order.client %}
                                    <td>{{ order.client.first_name }}</td>
                                {% else %}
                                    <td>Não associado a um Cliente</td>
                                {% endif %}
                                <td>{{ order.status }}</td>
                                <td>{{ order.total_price }}</td>
                                <td>
                                    {% if order.orderitem_set.exists %}
                                        <table>
                                            <tr>
                                                <th>Produto</th>
                                                <th>Quantidade</th>
                                                <th>Preço Unitário</th>
                                                <th>Total</th>
                                            </tr>
                                            {% for order_item in order.orderitem_set.all %}
                                                <tr>
                                                    <td>{{ order_item.product.name }}</td>
                                                    <td>{{ order_item.quantity }}</td>
                                                    <td>{{ order_item.unitary_price }}</td>
                                                    <td>{{ order_item.valor_dos_produtos }}</td>
                                                </tr>
                                            {% endfor %}
                                        </table>
                                    {% else %}
                                        Sem pedidos de item associados.
                                    {% endif %}
                                <td>
                                    <a href="{% url 'orders:delete_order' order.id %}" class="btn btn-danger btn-sm ">Excluir Pedido (não exclui P.I.)</a>
                                <td>
                                    <a href="{% url 'orders:edit_order' order.id %}" class="btn btn-primary btn-sm">Editar Pedido</a>
                                </td>
                                </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}