apps/clients/urls.py
from django.urls import path, include
from . import views
app_name = 'clients'

urlpatterns = [
    path('', views.list_clients, name='list_clients'),
    path('adicionar/', views.add_client, name='add_client'),
    path('editar/<int:id_client>/', views.edit_client, name='edit_client'),
    path('excluir/<int:id_client>/', views.delete_client, name='delete_client'),
]

projetolojaapp/urls.py
from django.contrib import admin
admin.autodiscover()
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('produtos/', include('products.urls', namespace='products')),
    path('redessociais/', include('socialnetworks.urls', namespace='socialnetworks')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('clientes_redessociais/', include('clients.urls', namespace='clients_socialnetworks')),
    path('pedidos/', include('orders.urls', namespace='orders')),
    path('pedidos_itens/', include('orders.itens_urls', namespace='orders_itens')),
]

apps/clients/models.py
from django.db import models
from socialnetworks.models import Socialnetwork

# Create your models here.

class Client(models.Model):
    first_name = models.CharField('Nome', max_length=50)
    last_name = models.CharField('Sobrenome', max_length=100) 
    address = models.CharField('Endereco', max_length=200)   
    cell_phone = models.CharField('Telefone celular', max_length=20)
    email = models.EmailField('E-mail',null=False, blank=False)
    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro'),
    )
    gender = models.CharField('Genero', max_length=1, choices=GENDER_CHOICES)
    client_socialnetwork = models.ManyToManyField(Socialnetwork, through='ClientSocialnetwork', blank=True)

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering =['id']
        managed = True
        db_table = 'clients'

    def __str__(self):
        return self.first_name



class ClientSocialnetwork(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    socialnetwork = models.ForeignKey(Socialnetwork, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Item de Redes Social'
        verbose_name_plural = 'Itens de Rede Social'
        ordering =['id']

    def __str__(self):
        return self.socialnetwork.name 

apps/clients/forms.py
from django import forms
from .models import Client

class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        exclude = ()

apps/clients/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Client, ClientSocialnetwork
from rest_framework import viewsets
from .serializer import ClientSerializer, ClientSocialnetworkSerializer
from .forms import ClientForm

# Create your views here.

def add_client(request):
    template_name = 'clients/add_client.html'
    context = {}
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('clients:list_clients')
    form = ClientForm()
    context['form'] = form
    return render(request, template_name, context)

def list_clients(request):
    template_name = 'clients/list_clients.html'
    clients = Client.objects.all()
    context = {
        'clients': clients
    }
    return render(request, template_name, context)

def edit_client(request, id_client):
    template_name = 'clients/add_client.html'  
    context = {}
    client = get_object_or_404(Client, id=id_client)
    if request.method == 'POST':
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            return redirect('clients:list_clients')
    form = ClientForm(instance=client)
    context['form'] = form
    return render(request, template_name, context)

def delete_client(request, id_client):
    client = Client.objects.get(id=id_client)
    client.delete()
    return redirect('clients:list_clients')

templates/clients/add_client.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Adicionar Cliente - {{ block.super }}
{% endblock title %}

{% block body %}
{{ block.super }}

    <div class="container">
        <br />
        <h5><b>Adicionar Novo Cliente</b></h5>
        <div class="row">
            <div class="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.first_name.id_for_label }}">Nome</label>
                        {{ form.first_name|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                        {{ form.last_name|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.address.id_for_label }}">Endereço</label>
                        {{ form.address|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.cell_phone.id_for_label }}">Telefone Celular</label>
                        {{ form.cell_phone|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.email.id_for_label }}">E-mail</label>
                        {{ form.email|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.gender.id_for_label }}">Gênero</label>
                        {{ form.gender|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

templates/clients/list_clients.html
{% extends 'base.html' %}

{% block title %}
    Lista de Clientes - {{ block.super }}
{% endblock title %}

{% block body %}
{{ block.super }}
    <div class="container">
        <br />
        <h5><b>Lista de Clientes</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                <a href="{% url 'clients:add_client' %}" class="btn btn-primary">Cadastrar novo cliente</a>
                <br /><br />
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Sobrenome</th>
                            <th scope="col">Endereço</th>
                            <th scope="col">Telefone</th>
                            <th scope="col">Email</th>
                            <th scope="col">Gênero</th>
                            <th scope="col">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for client in clients %}
                            <tr>
                                <th scope="row">{{ client.id }}</th>
                                <td>{{ client.first_name }}</td>
                                <td>{{ client.last_name }}</td>
                                <td>{{ client.address }}</td>
                                <td>{{ client.cell_phone }}</td>
                                <td>{{ client.email }}</td>
                                <td>{{ client.gender }}</td>
                                <td>
                                    <a href="{% url 'clients:edit_client' client.id %}" class="btn btn-primary btn-sm">Editar</a>
                                    <a href="{% url 'clients:delete_client' client.id %}" class="btn btn-danger btn-sm">Excluir</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div> 
 {% endblock body %}